# permissions for end users to view groups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: group-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: proxyserver
    app.kubernetes.io/part-of: proxyserver
    app.kubernetes.io/managed-by: kustomize
  name: group-viewer-role
rules:
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - groups/status
  verbs:
  - get
