---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - groups/finalizers
  verbs:
  - update
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - groups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - authentication.kubeguard.dev
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
